# Site settings
title: My Forever Photos
email: sam@myforeverphotos.com
description: This is a test
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://myforeverphotos.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
